name: "Test the action"
on:
  push:
    branches:
      - jedi-test

jobs:
  test:
    runs-on: example-runnerdeploy-m8cqb-rwl6d
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: "./"

      - run: npm ci --prod
      - run: npm run build