name: "Test the action"
on:
  push:
    branches:
      - jedi-test

jobs:
  test:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: "./"

      - run: echo "hello"